/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Gbveu6rb0ke
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Comfortaa } from 'next/font/google'
import { Gabarito } from 'next/font/google'

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Contact } from "./contact"

export function MainPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <nav className="header">
        <div className="container mx-auto flex flex-col items-center md:flex-row md:justify-between">
            <ul className="flex space-x-4">
              <li>
                <Link className="hover:text-gray-400" href="#">
                  About
                </Link>
              </li>
              <li>
                <Link className="hover:text-gray-400" href="#">
                  Skills
                </Link>
              </li>
              <li>
                <Link className="hover:text-gray-400" href="#">
                  Experience
                </Link>
              </li>
              <li>
                <Link className="hover:text-gray-400" href="#">
                  Projects
                </Link>
              </li>
              <li>
                <Link className="hover:text-gray-400" href="#">
                  Contact
                </Link>
              </li>
            </ul>

        </div>
      </nav>
      <main className="flex-1">
        <section className="test">
          <div className="full-screen-background">
        <div className="container mx-auto flex flex-col items-center md:flex-row md:justify-between  ">
          <div className="flex flex-col items-center md:items-start">
            <h1 className="text-3xl  main-title">Bonjour, je m'appelle Thomas CERDERA</h1>
            <p className="text-gray-400">et je suis développeur Full Stack</p>
          </div>
        </div>
        </div>
        </section>
        <section className="grid grid-cols-2 gap-8 px-8 py-12 h-[500px] mx-auto">
        <div className="mx-auto">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">About Me</h2>
          <p className="text-gray-600">
            I am a passionate full stack developer with experience in building scalable and user-friendly web
            applications. I have a strong background in both front-end and back-end technologies, and I'm always eager
            to learn new skills and stay up-to-date with the latest industry trends.
          </p>
        </div>
        {/* <div>
          <h2 className="text-2xl font-bold mb-4">Functional Competencies</h2>
          <ul className="grid grid-cols-2 gap-4">
            <li className="bg-gray-100 rounded-md p-4">
              <h3 className="text-lg font-bold">Front-end</h3>
              <p className="text-gray-600">React, Vue.js, Angular, HTML, CSS, JavaScript, TypeScript</p>
            </li>
            <li className="bg-gray-100 rounded-md p-4">
              <h3 className="text-lg font-bold">Back-end</h3>
              <p className="text-gray-600">Node.js, Express, Ruby on Rails, PHP, Python, Django</p>
            </li>
            <li className="bg-gray-100 rounded-md p-4">
              <h3 className="text-lg font-bold">Databases</h3>
              <p className="text-gray-600">MySQL, PostgreSQL, MongoDB, Redis, SQLite</p>
            </li>
            <li className="bg-gray-100 rounded-md p-4">
              <h3 className="text-lg font-bold">DevOps</h3>
              <p className="text-gray-600">Docker, Kubernetes, AWS, Azure, GCP, CI/CD</p>
            </li>
          </ul>
        </div> */}
      </section>
        <section className="bg-gray-100 py-12 px-4 md:px-8" id="skills">
          <div className="container mx-auto text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Skills</h2>
            <p className="max-w-[700px] mx-auto text-gray-500 md:text-xl">
                Explore my diverse work experience as a web developer, from startups to enterprise-level companies.
              </p>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="flex flex-col items-center">
                <CodepenIcon className="w-12 h-12 mb-2" />
                <p className="text-gray-700">React</p>
              </div>
              <div className="flex flex-col items-center">
                <CodepenIcon className="w-12 h-12 mb-2" />
                <p className="text-gray-700">Node.js</p>
              </div>
              <div className="flex flex-col items-center">
                <DatabaseIcon className="w-12 h-12 mb-2" />
                <p className="text-gray-700">MongoDB</p>
              </div>
              <div className="flex flex-col items-center">
                <DatabaseIcon className="w-12 h-12 mb-2" />
                <p className="text-gray-700">PostgreSQL</p>
              </div>
              <div className="flex flex-col items-center">
                <TypeIcon className="w-12 h-12 mb-2" />
                <p className="text-gray-700">TypeScript</p>
              </div>
              <div className="flex flex-col items-center">
                <DockIcon className="w-12 h-12 mb-2" />
                <p className="text-gray-700">Docker</p>
              </div>
              <div className="flex flex-col items-center">
                <CloudIcon className="w-12 h-12 mb-2" />
                <p className="text-gray-700">AWS</p>
              </div>
              <div className="flex flex-col items-center">
                <GitGraphIcon className="w-12 h-12 mb-2" />
                <p className="text-gray-700">Git</p>
              </div>
            </div>
          </div>
        </section>
        <section id="experience" className="w-full py-12 md:py-24 lg:py-32 bg-white">
          <div className="container px-4 md:px-6 mx-auto">
            <div className="space-y-4 text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Professional Journey</h2>
              <p className="max-w-[700px] mx-auto text-gray-500 md:text-xl">
                Explore my diverse work experience as a web developer, from startups to enterprise-level companies.
              </p>
            </div>
            <div className="mt-12 relative">
              <div className="absolute inset-0 w-px bg-gray-300 ml-6 md:ml-0 md:left-1/2 md:-translate-x-1/2" />
              <div className="grid gap-8">
                <div className="grid md:grid-cols-2 gap-4 relative">
                  <div className="bg-gray-100  rounded-lg p-6 space-y-2 md:ml-12">
                    <h3 className="text-xl font-bold">Web Developer</h3>
                    <p className="text-gray-500">Acme Inc.</p>
                    <p className="text-gray-600">2020 - Present</p>
                    <p className="text-gray-500">
                      Developed and maintained complex web applications using modern technologies like React, Node.js,
                      and GraphQL. Collaborated with cross-functional teams to deliver high-quality, user-centric
                      solutions.
                    </p>
                  </div>
                  <div className="absolute -left-6 md:left-1/2 md:-translate-x-1/2 bg-blue-400 rounded-full w-6 h-6 flex items-center justify-center">
                  </div>
                </div>
                <div className="grid md:grid-cols-2 gap-4 relative">
                  <div className="bg-gray-100 rounded-lg p-6 space-y-2 md:mr-12 md:col-start-2">
                    <h3 className="text-xl font-bold">Frontend Engineer</h3>
                    <p className="text-gray-500">Oceanic Startup</p>
                    <p className="text-gray-600">2018 - 2020</p>
                    <p className="text-gray-500">
                      Designed and implemented responsive user interfaces for a cutting-edge marine technology platform.
                      Optimized performance and accessibility, contributing to the company's growth and success.
                    </p>
                  </div>
                  <div className="absolute -left-6 md:left-1/2 md:-translate-x-1/2 bg-blue-400 rounded-full w-6 h-6 flex items-center justify-center">
                  </div>
                </div>
                <div className="grid md:grid-cols-2 gap-4 relative">
                  <div className="bg-gray-100 rounded-lg p-6 space-y-2 md:ml-12">
                    <h3 className="text-xl font-bold">Web Intern</h3>
                    <p className="text-gray-500">Space Exploration Inc.</p>
                    <p className="text-gray-600">2017 - 2018</p>
                    <p className="text-gray-500">
                      Gained valuable experience in building and maintaining web applications for a leading space
                      technology company. Contributed to the development of interactive data visualizations and
                      educational resources.
                    </p>
                  </div>
                  <div className="absolute -left-6 md:left-1/2 md:-translate-x-1/2 bg-blue-400 rounded-full w-6 h-6 flex items-center justify-center">
                  </div>
                </div>
                <div className="grid md:grid-cols-2 gap-4 relative">
                  <div className="bg-gray-100 rounded-lg p-6 space-y-2 md:mr-12 md:col-start-2">
                    <h3 className="text-xl font-bold">Web Developer Intern</h3>
                    <p className="text-gray-500">Aquatic Solutions</p>
                    <p className="text-gray-600">2016 - 2017</p>
                    <p className="text-gray-500">
                      Participated in the development of a web-based platform for marine research and conservation.
                      Gained experience in working with various web technologies and collaborating with a
                      multidisciplinary team.
                    </p>
                  </div>
                  <div className="absolute -left-6 md:left-1/2 md:-translate-x-1/2 bg-blue-400 rounded-full w-6 h-6 flex items-center justify-center">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-gray-100 py-12 px-4 md:px-8" id="projects">
          <div className="container mx-auto text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Projects</h2>
            <p className="max-w-[700px] mx-auto text-gray-500 md:text-xl">
                Explore my diverse work experience as a web developer, from startups to enterprise-level companies.
              </p>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              <Card>
                <img
                  alt="Project 1"
                  className="rounded-t-lg"
                  height={300}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/300",
                    objectFit: "cover",
                  }}
                  width={400}
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold mb-2">Project 1</h3>
                  <p className="text-gray-700">
                    A full-stack web application built with React, Node.js, and MongoDB. Includes features like user
                    authentication, real-time chat, and data visualization.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <img
                  alt="Project 2"
                  className="rounded-t-lg"
                  height={300}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/300",
                    objectFit: "cover",
                  }}
                  width={400}
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold mb-2">Project 2</h3>
                  <p className="text-gray-700">
                    A responsive e-commerce website built with Next.js, TypeScript, and PostgreSQL. Includes features
                    like product listings, shopping cart, and order management.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <img
                  alt="Project 3"
                  className="rounded-t-lg"
                  height={300}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/300",
                    objectFit: "cover",
                  }}
                  width={400}
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold mb-2">Project 3</h3>
                  <p className="text-gray-700">
                    A mobile-first web application built with React Native, Node.js, and MongoDB. Includes features like
                    location-based services, push notifications, and offline support.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-12 px-4 md:px-8" id="contact">
          <div className="container mx-auto text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Contact</h2>
            <p className="max-w-[700px] mx-auto text-gray-500 md:text-xl">
                Explore my diverse work experience as a web developer, from startups to enterprise-level companies.
              </p>
            <Contact></Contact>
          </div>
        </section>
      </main>
      <footer className="bg-gray-900 text-white py-4 px-4 md:px-8">
        <div className="container mx-auto flex justify-between items-center">
          <p>© 2024 Thomas CERDERA. All rights reserved.</p>
          <div className="flex space-x-4">
            <Link className="hover:text-gray-400" href="#">
              <GithubIcon className="w-6 h-6" />
            </Link>
            <Link className="hover:text-gray-400" href="#">
              <LinkedinIcon className="w-6 h-6" />
            </Link>
            <Link className="hover:text-gray-400" href="#">
              <TwitterIcon className="w-6 h-6" />
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function CloudIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
    </svg>
  )
}


function CodepenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2" />
      <line x1="12" x2="12" y1="22" y2="15.5" />
      <polyline points="22 8.5 12 15.5 2 8.5" />
      <polyline points="2 15.5 12 8.5 22 15.5" />
      <line x1="12" x2="12" y1="2" y2="8.5" />
    </svg>
  )
}


function DatabaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  )
}


function DockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 8h20" />
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="M6 16h12" />
    </svg>
  )
}


function GitGraphIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="5" cy="6" r="3" />
      <path d="M5 9v6" />
      <circle cx="5" cy="18" r="3" />
      <path d="M12 3v18" />
      <circle cx="19" cy="6" r="3" />
      <path d="M16 15.7A9 9 0 0 0 19 9" />
    </svg>
  )
}


function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function TypeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="4 7 4 4 20 4 20 7" />
      <line x1="9" x2="15" y1="20" y2="20" />
      <line x1="12" x2="12" y1="4" y2="20" />
    </svg>
  )
}
